//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortafolioNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.FUNCIONARIO = new HashSet<FUNCIONARIO>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_CIUDAD { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO { get; set; }
    }
}
