//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortafolioNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public FUNCIONARIO()
        {
            this.DIA = new HashSet<DIA>();
            this.HORA = new HashSet<HORA>();
            this.PEDIDO_A_BODEGA = new HashSet<PEDIDO_A_BODEGA>();
            this.HIST_ATENCION = new HashSet<HIST_ATENCION>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal RUT { get; set; }
        public string DV { get; set; }
        public string P_NOMBRE { get; set; }
        public string S_NOMBRE { get; set; }
        public string P_APELLIDO { get; set; }
        public string S_APELLIDO { get; set; }
        public System.DateTime FECHA_NAC { get; set; }
        public string SEXO { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public decimal ID_COMUNA { get; set; }
        public decimal ID_USUARIO { get; set; }
        public decimal ID_TIPO { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<DIA> DIA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual TIPO_FUNCIONARIO TIPO_FUNCIONARIO { get; set; }
        public virtual ICollection<HORA> HORA { get; set; }
        public virtual ICollection<PEDIDO_A_BODEGA> PEDIDO_A_BODEGA { get; set; }
        public virtual ICollection<HIST_ATENCION> HIST_ATENCION { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
