//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortafolioNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_A_BODEGA
    {
        public decimal ID { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal RUT_EMISOR { get; set; }
        public decimal ESTADO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
    }
}
